/* Rename some country names to match the country names from that commodity table */
update country set geounit='Burma (Rep of the Union of Myanmar)' where geounit='Myanmar';
update country set geounit='Cote d''Ivoire' where geounit='Ivory Coast';
update country set geounit='Democratic People''s Republic of Korea' where geounit='North Korea';
update country set geounit='FYR Macedonia' where geounit='Macedonia';
update country set geounit='Guinea-Bissau' where geounit='Guinea Bissau';
update country set geounit='Hong Kong (SAR of China)' where geounit='Hong Kong S.A.R.';
update country set geounit='Macau (SAR of China)' where geounit='Macao S.A.R';
update country set geounit='Republic of Korea' where geounit='South Korea';
update country set geounit='Wallis & Futuna Island' where geounit='Wallis and Futuna';
update country set geounit='Slovak Republic' where geounit='Slovakia';
update country set geounit='Montenegro' where geounit='Montenegro';
update country set geounit='Serbia & Montenegro' where geounit='Montenegro';
update country set geounit='Serbia' where geounit='Republic of Serbia';
update country set geounit='French Guiana' where geounit='French Guiana';
update country set geounit='Bahamas' where geounit='The Bahamas';
update country set geounit='Antigua & Barbuda' where geounit='Antigua and Barbuda';
update country set geounit='Bosnia-Herzegovina' where geounit='Bosnia and Herzegovina';
update country set geounit='United States' where geounit='United States of America';
update country set geounit='Trinidad & Tobago' where geounit='Trinidad and Tobago';
update country set geounit='Russian Federation' where geounit='Russia';
